### ISSUE TITLE
Add gatsby-plugin-sitemap

### ISSUE THREAD

**Issue by chrfritsch** [molebox/gatsby-theme-seo#1]
I think gatsby-plugin-sitemap is a good plugin that should be part of this theme. If you agree, I would like to open a PR.

**Comment by molebox** [comment]
> I think gatsby-plugin-sitemap is a good plugin that should be part of this theme. If you agree, I would like to open a PR.

Hey! Yeah thats a good shout. Feel free to open a PR 🙌🏻
